<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Remember Me_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>ab665191-c71f-4481-8283-74aa1685054a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;lagom page-login page-login-secondary lagom-not-portal lagom-layout-top lagom-default page-login&quot;]/div[@class=&quot;app-main&quot;]/div[@class=&quot;main-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;login-body&quot;]/form[@class=&quot;login-form&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;checkbox m-b-2x hover&quot;]/div[@class=&quot;checkbox-styled hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
   </webElementXpaths>
</WebElementEntity>
